export const SET_PLAYER_RESOURCES = '@player/SET_PLAYER_RESOURCES';
export const SET_PLAYER_MULTIPLIERS = '@player/SET_PLAYER_MULTIPLIERS';
export const SET_PLAYER_TIMES = '@player/SET_PLAYER_TIMES';
export const SET_PLAYER_HEROES = '@player/SET_PLAYER_HEROES';
