const CURRENCIES = {
    GOLD: 'GOLD',
    DIAMOND: 'DIAMOND',
    XP: 'XP',
    WATER_ESSENCE: 'WATER_ESSENCE',
    FIRE_ESSENCE: 'FIRE_ESSENCE',
    EARTH_ESSENCE: 'EARTH_ESSENCE',
    WIND_ESSENCE: 'WIND_ESSENCE',
    WATER_GEM: 'WATER_GEM',
    FIRE_GEM: 'FIRE_GEM',
    EARTH_GEM: 'EARTH_GEM',
    WIND_GEM: 'WIND_GEM',
};

export { CURRENCIES };
