const RARITIES = {
    COMMON: 'COMMON',
    RARE: 'RARE',
    EPIC: 'EPIC',
    LEGENDARY: 'LEGENDARY',
};

const QUALITIES = {
    COMMON: 'COMMON',
    RARE: 'RARE',
    EPIC: 'EPIC',
    LEGENDARY: 'LEGENDARY',
    MYTHIC: 'MYTHIC',
    DIVINE: 'DIVINE',
};

const ELEMENTS = {
    WATER: 'WATER',
    FIRE: 'FIRE',
    EARTH: 'EARTH',
    WIND: 'WIND',
};

const TYPES = {
    BEAST: 'BEAST',
    UNDEAD: 'UNDEAD',
    CELESTIAL: 'CELESTIAL',
};

const RACES = {
    DRAGON: 'DRAGON',
    CENTAUR: 'CENTAUR',
    SKELETON: 'SKELETON',
    ANGEL: 'ANGEL',
};

const SKILL_TYPE = {
    ULTIMATE: 'ULTIMATE',
    ACTIVE: 'ACTIVE',
    PASSIVE: 'PASSIVE',
};

export { RARITIES, ELEMENTS, QUALITIES, TYPES, RACES, SKILL_TYPE };
