const CURRENCIES = {
    GOLD: 'GOLD',
    DIAMOND: 'DIAMOND',
    XP: 'XP',
    WATER_ESSENCE: 'WATER_ESSENCE',
    FIRE_ESSENCE: 'FIRE_ESSENCE',
    EARTH_ESSENCE: 'EARTH_ESSENCE',
    WIND_ESSENCE: 'WIND_ESSENCE',
    WATER_GEM: 'WATER_GEM',
    FIRE_GEM: 'FIRE_GEM',
    EARTH_GEM: 'EARTH_GEM',
    WIND_GEM: 'WIND_GEM',
};

const RARITIES = {
    COMMON: 'COMMON',
    RARE: 'RARE',
    EPIC: 'EPIC',
    LEGENDARY: 'LEGENDARY',
};

const QUALITIES = {
    COMMON: 'COMMON',
    RARE: 'RARE',
    EPIC: 'EPIC',
    LEGENDARY: 'LEGENDARY',
    MYTHIC: 'MYTHIC',
    DIVINE: 'DIVINE',
};

const ELEMENTS = {
    WATER: 'WATER',
    FIRE: 'FIRE',
    EARTH: 'EARTH',
    WIND: 'WIND',
};

const TYPES = {
    BEAST: 'BEAST',
    UNDEAD: 'UNDEAD',
    CELESTIAL: 'CELESTIAL',
};

const RACES = {
    DRAGON: 'DRAGON',
    CENTAUR: 'CENTAUR',
    SKELETON: 'SKELETON',
    ANGEL: 'ANGEL',
};

const SKILL_TYPE = {
    ULTIMATE: 'ULTIMATE',
    ACTIVE: 'ACTIVE',
    PASSIVE: 'PASSIVE',
};

export { CURRENCIES, RARITIES, ELEMENTS, QUALITIES, TYPES, RACES, SKILL_TYPE };
